import os
from dotenv import load_dotenv
from google import genai

load_dotenv()

api_key = os.getenv("GEMINI_API_KEY")

if not api_key:
    raise ValueError("GEMINI_API_KEY not found in .env file")

client = genai.Client(api_key=api_key)


def analyze_resume(resume_text):

    prompt = f"""
You are an experienced HR recruiter.

Analyze the following resume and provide constructive feedback.

Return your response exactly in this format:

Overall Score: X/10

Strengths:
- Point 1
- Point 2
- Point 3

Weaknesses:
- Point 1
- Point 2

Suggestions:
- Point 1
- Point 2
- Point 3

Resume:

{resume_text}
"""

    try:
        response = client.models.generate_content(
            model="gemini-2.0-flash",
            contents=prompt
        )

        if response.text:
            return response.text

        return "No response was generated by Gemini."

    except Exception as e:
        print("\n========== GEMINI ERROR ==========")
        print(e)
        print("==================================\n")

        return f"Gemini Error: {str(e)}"